### ISSUE TITLE
鼠标跟键盘处理sync版有吗

### ISSUE THREAD

**Issue by zenghh** [ClericPy/ichrome#110]
如题

**Comment by ClericPy** [comment]
sync 已经落后两个大版本了, 早期就处于 deprecated 半废弃状态了... 同时维护两个版本挺麻烦的, 主要还是我一开始实体抽象做的不好, 导致了 async 版本的维护起来都很脏, 该项目帮助我在上一份工作实现了 Facebook 分布式养号, 换了工作以后就没再碰过.

**Comment by zenghh** [comment]
好的，谢谢
