### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by bpkddr** [ClericPy/ichrome#115]
Hi dev,

How to upload file without input file selector?

I mean to change file field.

**Comment by bpkddr** [comment]
for example : i need to upload media on meta business suite ( facebook )
check attachment, hasn't input file selector, its just button
![Screenshot_263](https://user-images.githubusercontent.com/53825262/208059232-9e4c3961-4295-4c8c-931b-edc385f1f8be.jpg)

**Comment by ClericPy** [comment]
Have you looking for file type `input` tag in DOM? Sometimes it is hidden and invisible but can be found in document.

I can't open a demo URL to solve this issue, and `ichrome` is no more than `Chrome DevTools Protocol`.
