### ISSUE TITLE
如何设置 Geo Location 或者确认地理位置授权

### ISSUE THREAD

**Issue by why2lyj** [ClericPy/ichrome#117]
请教一下，有些网站要求浏览器授权地理位置，需要如何设置？

或者我想执行 CDP 命令达到设置目的，应该如何处理？

![image](https://user-images.githubusercontent.com/31466760/217712077-aca1010c-1b8a-449b-a601-e63df24e1cda.png)

发现并没有方法，耐心研究了下，自己自足了 :)

**Comment by ClericPy** [comment]
不了解是什么指纹浏览器, 这个主要就是当年没其他框架用的时候摸索着玩的. 调起的是原生的 chrome/Chromium 浏览器

**Comment by why2lyj** [comment]
还是非常感谢，这个仓库启蒙了我一些东西，给了非常好的idea。
