### ISSUE TITLE
能实现page.setRequestInterception吗？

### ISSUE THREAD

**Issue by tmxd09887** [ClericPy/ichrome#122]
类似puppeteer的page.setRequestInterception

想这样使用
await page.setRequestInterception(true)
page.on('request', async request => {
    if (...）{}else{
        request.continue()
    }
})

**Comment by ClericPy** [comment]
https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setRequestInterception

Sets the requests to intercept that match the provided patterns and optionally resource types. Deprecated, please use Fetch.enable instead.

早就弃用了吧, 改用 Fetch 吧 https://clericpy.github.io/ichrome/reference/AsyncTab/#ichrome.async_utils.AsyncTab.iter_fetch
