### ISSUE TITLE
[SUGGESTION] It should download the chromium automatically if it's not installed on the server

### ISSUE THREAD

**Issue by juanfrilla** [ClericPy/ichrome#128]

**Comment by ClericPy** [comment]
here are three ways to do that
1. install by yourself:
`python -m ichrome --install=/chrome_path` and set the chrome_path arg with that `/chrome_path/chrome`

2. use docker:
use the docker image with `chromium`, and set the chrome path with the real chrome_path of chrome bin.

3. use playwright

**Comment by juanfrilla** [comment]
@ClericPy I have a chromium-browser that is on usr/bin/chromium-browser, how can I tell ichrome to use it?

**Comment by ClericPy** [comment]
1. ensure it's a right path: `/usr/bin/chromium-browser --version` or  `/usr/bin/chromium-browser/chrome --version`
2. AsyncChromeDaemon has the chrome_path arg

**Comment by juanfrilla** [comment]
yeah thanks @ClericPy now it worked and the last thing, what is this message?
`Cannot connect to host 127.0.0.1:9222 ssl:default [Connect call failed ('127.0.0.1', 9222)].`

**Comment by ClericPy** [comment]
I never seen that ssl issue. Is it the fatal error or only a warning? maybe it happens while openssl install issue

**Comment by ClericPy** [comment]
1. upgrade your openssl version
2. change the 9222 port to other ports
3. some Permission issue?
