### ISSUE TITLE
Fail auto login google

### ISSUE THREAD

**Issue by snja** [ClericPy/ichrome#44]
auto login google fails if it is covered by other chrome?
any solution?

**Comment by ClericPy** [comment]
I've no idea what you said, and login info(like Cookie, Cache) is saved on different user dir folders.

So use a stand-alone `user_data_dir` may give a hand?

**Comment by bpkddr** [comment]
we do the task of automatically filling in the email/password input

but when at the same time we are working on another chrome window (manually) and its covered the chrome window ( from ichrome ), the input input task fails to execute

**Comment by ClericPy** [comment]
> we do the task of automatically filling in the email/password input
> 
> but when at the same time we are working on another chrome window (manually) and its cover the chrome window ( from ichrome ), the input task fails to execute

If you want to avoid reusing Chrome process, try using a different port and user_data_dir, these two args will make them be connected to the same Chrome instance
