### ISSUE TITLE
How could I use Runtime.compileScript in ichrome?

### ISSUE THREAD

**Issue by Champollion9012** [ClericPy/ichrome#46]
I want to use this method(Runtime.compileScript) from Chrome DevTools Protocol in ichrome.
How could I use Runtime.compileScript in ichrome?
I just know the `tab.js()`.
Could you give me an example?

btw, `Debugger.setBreakpoint` this method, I also need.

**Comment by ClericPy** [comment]
Those are not default methods for it is not very common usage.

You can do like this: `data = await tab.send('Runtime.compileScript', expression='xxx', sourceURL='xxx')`

**Comment by Champollion9012** [comment]
Thx

**Comment by ClericPy** [comment]
you're welcome
