### ISSUE TITLE
How could I show some local variables in javascript with ichrome?

### ISSUE THREAD

**Issue by Champollion9012** [ClericPy/ichrome#48]
Sorry, I know this question that is related to Chrome DevTools Protocol.
But, I help you can help me. :(

I'd like to get some local variables in a javascript function.
My idea is setting some breakpoints, executing and then showing the debugger.scope to capture the local variables.
However, I don't know how to start with ichrome....

**Comment by ClericPy** [comment]
That's a good question. Someone asked me last year, but I didn't try that yet. Maybe you can find the `objectId` of local functions by cdp.

Years before, I tried using `Fetch` method as a `Man-in-the-middle (MITM) attacks` to update those JS functions, and then add new hook code to them.

**Comment by Champollion9012** [comment]
Thank for reply. 
`Fetch` is `https://chromedevtools.github.io/devtools-protocol/tot/Fetch/`?
If it's, which method you would suggest? could you give me more concrete details?
And How to capture the `objectId`? 
Sorry, I'm an newbie.

**Comment by ClericPy** [comment]
Yup, Fetch could modify the response.

objectId you can learn it from google, I didn't use that before.
