### ISSUE TITLE
sync onload

### ISSUE THREAD

**Issue by ttygde** [ClericPy/ichrome#63]
Why add_js_onload is async only? Is there way to do it in sync tab?

**Comment by ttygde** [comment]
and using send command directly doesnt work, what am I missing?
self.chrome.tabs[0].send('Page.addScriptToEvaluateOnNewDocument', source="alert(0);")

**Comment by ClericPy** [comment]
> Why add_js_onload is async only? Is there way to do it in sync tab?

`sync utils` is deprecated in ichrome for no time to support two context (my bad, I should have abstracted the connector more completely).


> and using send command directly doesnt work, what am I missing?
> 
> ```
> chrome.tabs[0].send('Page.addScriptToEvaluateOnNewDocument', source="alert(0);")
> 
> INFO  2021-10-05 05:06:28 [ichrome] sync_utils.py(247): <Tab(chrome://newtab/)> send: {'method': 'Page.addScriptToEvaluateOnNewDocument', 'params': {'source': 'alert(0);'}, 'id': 1}
> INFO  2021-10-05 05:06:28 [ichrome] sync_utils.py(247): <Tab(chrome://newtab/)> send: {'method': 'Page.enable', 'params': {}, 'id': 1}
> INFO  2021-10-05 05:06:28 [ichrome] sync_utils.py(247): <Tab(https://bing.com)> send: {'method': 'Page.navigate', 'params': {'url': 'https://bing.com'}, 'id': 2}
> INFO  2021-10-05 05:06:28 [ichrome] sync_utils.py(247): <Tab(https://bing.com)> send: {'method': 'Page.enable', 'params': {}, 'id': 3}
> ```

`Page.enable` should be activated before other methods of `Page`.

PS: maybe you can check microsoft's https://github.com/microsoft/playwright-python for the sync mode usage.

**Comment by ttygde** [comment]
Thanks!

**Comment by ttygde** [comment]
Still can't get it working. 
```
browser = Chrome(host="127.0.0.1", port=9222, timeout=3, retry=1)
browser.tabs[0].send('Page.enable')
source = 'console.log("injected"); alert(0);'
browser.tabs[0].send('Page.addScriptToEvaluateOnNewDocument', source=source)
browser.tabs[0].set_url('https://bing.com', timeout=5)

INFO  2021-10-06 05:36:26 [ichrome] sync_utils.py(247): <Tab(chrome://newtab/)> send: {'method': 'Page.enable', 'params': {}, 'id': 1}
INFO  2021-10-06 05:36:26 [ichrome] sync_utils.py(247): <Tab(chrome://newtab/)> send: {'method': 'Page.addScriptToEvaluateOnNewDocument', 'params': {'source': 'console.log("injected"); alert(0);'}, 'id': 1}
INFO  2021-10-06 05:36:26 [ichrome] sync_utils.py(247): <Tab(chrome://newtab/)> send: {'method': 'Page.enable', 'params': {}, 'id': 1}
INFO  2021-10-06 05:36:26 [ichrome] sync_utils.py(247): <Tab(https://bing.com)> send: {'method': 'Page.navigate', 'params': {'url': 'https://bing.com'}, 'id': 2}
INFO  2021-10-06 05:36:28 [ichrome] sync_utils.py(247): <Tab(https://bing.com)> send: {'method': 'Page.enable', 'params': {}, 'id': 3}

```

**Comment by ClericPy** [comment]
I'll try this later

**Comment by ClericPy** [comment]
```

from ichrome import Chrome

browser = Chrome(host="127.0.0.1", port=9222, timeout=3, retry=1)
tab = browser.tabs[0]
tab.send('Page.enable')
source = 'console.log("injected"); alert(0);'
tab.send('Page.addScriptToEvaluateOnNewDocument', source=source)
tab.set_url('https://bing.com', timeout=5)
```

tab should not be tabs[0] multi times, because it need to keep only 1 websocket connection.
