### ISSUE TITLE
点击新链接后，怎么取得这个新链接产生的tab？

### ISSUE THREAD

**Issue by bluebad** [ClericPy/ichrome#71]
async with cd.connect_tab(index=1, auto_close=True) as tab:
我这样写，取得的tab却是和index=0一样的tab，打印len(await tab.chrome.tabs）确实有2个tab。

**Comment by ClericPy** [comment]
首先 index 0 代表的是当前 Activate 的那个标签页, 所以新标签页用 0 就好了. 一般情况都用 await tab.goto 来切换比较简单. 或者列出所有 tabs 按 url 找到对应的 tab

**Comment by bluebad** [comment]
感谢解答。可能这个部分有一个文档详述一下较好。

**Comment by ClericPy** [comment]
这一年多上班太忙了, 没大有时间写文档, 尽量放到代码注释里了

https://github.com/ClericPy/ichrome/blob/master/ichrome/daemon.py#L866

**Comment by bluebad** [comment]
> 这一年多上班太忙了, 没大有时间写文档, 尽量放到代码注释里了
> 
> https://github.com/ClericPy/ichrome/blob/master/ichrome/daemon.py#L866

嗯，辛苦了。这个包确实使使用CDP便利不少，功德一件。

**Comment by ClericPy** [comment]
> > 这一年多上班太忙了, 没大有时间写文档, 尽量放到代码注释里了
> > https://github.com/ClericPy/ichrome/blob/master/ichrome/daemon.py#L866
> 
> 嗯，辛苦了。这个包确实使使用CDP便利不少，功德一件。

主要我需要的时候其他的没的选, 微软那个其实应该还行, 不过用惯了自己的我所以一直没切过去
