### ISSUE TITLE
怎样键入Backspace？

### ISSUE THREAD

**Issue by bluebad** [ClericPy/ichrome#76]
试过tab.keyboard_send(string='\u0008')或者\b，都无效。

**Comment by ClericPy** [comment]
你想要做啥呢, 不能用 string, 得用不同系统的 keyCode 来发送, 具体参考官方 https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchKeyEvent
这里实际是发送键盘事件的方式

**Comment by bluebad** [comment]
让一个输入框往回删除几个字符，windows的backspace就是8，要怎么传参呢？

**Comment by ClericPy** [comment]
我挺长时间没用这功能了, 你看看官方方式吧
如果是我要处理输入框, 估计直接用 js 覆盖了...
