### ISSUE TITLE
how to disable this pop up?

### ISSUE THREAD

**Issue by bpkddr** [ClericPy/ichrome#78]
how to disable this pop up ( translate ) ?

![Screenshot_24](https://user-images.githubusercontent.com/53825262/146881707-39bbadb6-71ac-44c7-85ad-e11a99a11e9a.png)

**Comment by ClericPy** [comment]
`--disable-translate` or `--disable-features=Translate` as command line startup args? https://bugs.chromium.org/p/chromium/issues/detail?id=770776#c11

I didn't find how to disable that in https://chromedevtools.github.io/devtools-protocol/
