### ISSUE TITLE
not accepting proxies from zyte because ichrome not taking 'verify' kwarg

### ISSUE THREAD

**Issue by sacsbrainz** [ClericPy/ichrome#80]
hello i tried to use zyte proxy but its not working because they use ca cert to auth their proxy which ichrome doesnt support

in request module its 'verify' kwargs
example
import requests

``` 
response = requests.get(
    "https://httpbin.org/get",
    proxies={
        "http": "http://1kksksskskosmimiq:@proxy.crawlera.com:8011/",
        "https": "http://1kksksskskosmimiq:@proxy.crawlera.com:8011/",
    },
    verify='/path/to/zyte-proxy-ca.crt' 
)
print(response.text)
```

but ichrome do not have 'verify'

**Comment by ClericPy** [comment]
Chrome self not support authed proxy.

So I used `gost` for a forward proxy, this is quite a Trouble

**Comment by sacsbrainz** [comment]
> 

Any guidance will be really appreciated 
On how to use the gost with ichrome i really want to use this project 

Other software have easy work around but i have decided i must use ichrome

**Comment by ClericPy** [comment]
https://github.com/ginuerzh/gost/blob/master/README_en.md

gost -L 127.0.0.1:9999 -F http://xxx@xxx:a.com

port-forwarding proxy for chrome, `python3 -m ichrome --proxy=http://127.0.0.1:9999`

**Comment by sacsbrainz** [comment]
Ok thanks let me give it a try

**Comment by ClericPy** [comment]
https://github.com/ClericPy/ichrome/issues/86

Use `Fetch.enable` to handle all the requests and pass the auth info with `Fetch.authRequired`
