### ISSUE TITLE
using a chrome extension with ichrome

### ISSUE THREAD

**Issue by sacsbrainz** [ClericPy/ichrome#82]
can i install a chrome extension ?
and connect the extension(metamask)

**Comment by sacsbrainz** [comment]
trying to install  this extension 
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en

@ClericPy 
@auphofBSF

**Comment by ClericPy** [comment]
Ichrome is only a connector for https://chromedevtools.github.io/devtools-protocol/ , and no more than that.

Try installing the extension manually.
