### ISSUE TITLE
how to interact with iframe?

### ISSUE THREAD

**Issue by bpkddr** [ClericPy/ichrome#83]
hi,

how to interact to iframe, scroll, clict, etc?

thank before,

**Comment by ClericPy** [comment]
This is an advanced usage, you can find some information here: https://chromedevtools.github.io/devtools-protocol/tot/DOM/#type-Node

If it is a non-cross-domain iframe, you can also use JS to do that: https://stackoverflow.com/questions/19498725/control-iframe-content-with-javascript-html

But in my experience, I do it by opening a new tab with the iframe's src.
