### ISSUE TITLE
Can I listen for browser pop-ups? Does it also support writing your own browser fingerprint

### ISSUE THREAD

**Issue by Liuyilin-ai** [ClericPy/ichrome#88]

**Comment by ClericPy** [comment]
```await tab.handle_dialog(accept=True)``` 
https://github.com/ClericPy/ichrome/blob/af2d4e17cdc3cc4d871069c5a835f19f81a349a1/examples_async.py#L162

I used to handle browser fingerprinting by using a different one-time user directory, depending on the fingerprinting algorithm
